### ISSUE TITLE
sregistry images throws error

### ISSUE THREAD

**Issue by iferres** [singularityhub/sregistry-cli#264]
**Describe the bug**

I installed sregistry client with `pip install sregistry[all]`, apparently successful installation. But I got this error when calling images:
```
sregistry images
Traceback (most recent call last):
  File "/home/iferres/.local/bin/sregistry", line 8, in <module>
    sys.exit(main())
  File "/home/iferres/.local/lib/python3.8/site-packages/sregistry/client/__init__.py", line 391, in main
    main(args=args, parser=parser, extra=extra)
  File "/home/iferres/.local/lib/python3.8/site-packages/sregistry/client/images.py", line 21, in main
    cli = get_client(quiet=args.quiet)
  File "/home/iferres/.local/lib/python3.8/site-packages/sregistry/main/__init__.py", line 131, in get_client
    cli = Client()
  File "/home/iferres/.local/lib/python3.8/site-packages/sregistry/main/hub/__init__.py", line 21, in __init__
    super(Client, self).__init__(**kwargs)
  File "/home/iferres/.local/lib/python3.8/site-packages/sregistry/main/base/__init__.py", line 60, in __init__
    self._init_db(SREGISTRY_DATABASE)
  File "/home/iferres/.local/lib/python3.8/site-packages/sregistry/database/models.py", line 159, in init_db
    self.engine = create_engine(self.database, convert_unicode=True)
  File "<string>", line 2, in create_engine
  File "/home/iferres/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/iferres/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 680, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'convert_unicode' sent to create_engine(), using configuration SQLiteDialect_pysqlite/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

**To Reproduce**
```
pip install sregistry[all]
sregistry images
```

**Expected behavior**
Expecting to return empty database since I haven't pulled any image yet.

**Version of Singularity and Singularity Registry Client**
```
sregistry --version
0.2.38
```
Ubuntu 20.04.1

**Comment by iferres** [comment]
Downgrading SQLAlchemy to 1.4.48 works.

**Comment by vsoch** [comment]
okay - that solution can work! Would you care to open a PR to do a <= for this version? We'd want to do that, bump the version, and add a note in the changelog (and probably will be a TODO to come back and update the call to a newer version at some point).

**Comment by iferres** [comment]
The file is ./sregistry/version.py ? Sorry, I'm not very familiar with python packaging. Would accept a `max_version` parameter instead of `min_version`?

**Comment by vsoch** [comment]
Yes! The version is here https://github.com/singularityhub/sregistry-cli/blob/994fd020680642dfa05249eb2fde599650920875/sregistry/version.py#L11 and that file will also be where you want to pin the version. And the CHANGELOG.md is in the root. And then here https://github.com/singularityhub/sregistry-cli/blob/994fd020680642dfa05249eb2fde599650920875/setup.py#L35-L39 we'd want to add the logic to set that up, something like:

```python
elif "max_version" in module_meta:
    dependency = "%s<=%s" %(module_name, module_meta['max_version'])
```
