### ISSUE TITLE
timezone package missing

### ISSUE THREAD

**Issue by shahzebsiddiqui** [singularityhub/sregistry-cli#44]
Tried installing sregistry-cli using development branch the installation went through but it fails on timezone. Package is missing

```
[root@hpcv21 sregistry-cli]# python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to sregistry.egg-info/requires.txt
writing sregistry.egg-info/PKG-INFO
writing top-level names to sregistry.egg-info/top_level.txt
writing dependency_links to sregistry.egg-info/dependency_links.txt
writing entry points to sregistry.egg-info/entry_points.txt
reading manifest file 'sregistry.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 4: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: no previously-included files matching '*.py[co]' found anywhere in distribution
warning: no previously-included files matching '*.img' found anywhere in distribution
warning: no previously-included files matching '*.simg' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
writing manifest file 'sregistry.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sregistry
copying build/lib/sregistry/__init__.py -> build/bdist.linux-x86_64/egg/sregistry
copying build/lib/sregistry/defaults.py -> build/bdist.linux-x86_64/egg/sregistry
copying build/lib/sregistry/version.py -> build/bdist.linux-x86_64/egg/sregistry
creating build/bdist.linux-x86_64/egg/sregistry/auth
copying build/lib/sregistry/auth/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/auth
copying build/lib/sregistry/auth/secrets.py -> build/bdist.linux-x86_64/egg/sregistry/auth
copying build/lib/sregistry/auth/utils.py -> build/bdist.linux-x86_64/egg/sregistry/auth
creating build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/add.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/delete.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/get.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/images.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/inspect.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/labels.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/list.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/pull.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/push.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/record.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/rm.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/rmi.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/search.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/share.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/shell.py -> build/bdist.linux-x86_64/egg/sregistry/client
copying build/lib/sregistry/client/singularity.py -> build/bdist.linux-x86_64/egg/sregistry/client
creating build/bdist.linux-x86_64/egg/sregistry/database
copying build/lib/sregistry/database/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/database
copying build/lib/sregistry/database/models.py -> build/bdist.linux-x86_64/egg/sregistry/database
copying build/lib/sregistry/database/sqlite.py -> build/bdist.linux-x86_64/egg/sregistry/database
copying build/lib/sregistry/database/robot.png -> build/bdist.linux-x86_64/egg/sregistry/database
creating build/bdist.linux-x86_64/egg/sregistry/logger
copying build/lib/sregistry/logger/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/logger
copying build/lib/sregistry/logger/message.py -> build/bdist.linux-x86_64/egg/sregistry/logger
copying build/lib/sregistry/logger/progress.py -> build/bdist.linux-x86_64/egg/sregistry/logger
copying build/lib/sregistry/logger/spinner.py -> build/bdist.linux-x86_64/egg/sregistry/logger
creating build/bdist.linux-x86_64/egg/sregistry/main
copying build/lib/sregistry/main/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main
creating build/bdist.linux-x86_64/egg/sregistry/main/__template__
copying build/lib/sregistry/main/__template__/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/__template__
copying build/lib/sregistry/main/__template__/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/__template__
copying build/lib/sregistry/main/__template__/push.py -> build/bdist.linux-x86_64/egg/sregistry/main/__template__
copying build/lib/sregistry/main/__template__/query.py -> build/bdist.linux-x86_64/egg/sregistry/main/__template__
copying build/lib/sregistry/main/__template__/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/__template__
creating build/bdist.linux-x86_64/egg/sregistry/main/base
copying build/lib/sregistry/main/base/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/base
copying build/lib/sregistry/main/base/auth.py -> build/bdist.linux-x86_64/egg/sregistry/main/base
copying build/lib/sregistry/main/base/headers.py -> build/bdist.linux-x86_64/egg/sregistry/main/base
copying build/lib/sregistry/main/base/http.py -> build/bdist.linux-x86_64/egg/sregistry/main/base
copying build/lib/sregistry/main/base/settings.py -> build/bdist.linux-x86_64/egg/sregistry/main/base
creating build/bdist.linux-x86_64/egg/sregistry/main/docker
copying build/lib/sregistry/main/docker/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/docker
copying build/lib/sregistry/main/docker/api.py -> build/bdist.linux-x86_64/egg/sregistry/main/docker
copying build/lib/sregistry/main/docker/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/docker
copying build/lib/sregistry/main/docker/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/docker
creating build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/push.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/query.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/share.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
copying build/lib/sregistry/main/google_drive/utils.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_drive
creating build/bdist.linux-x86_64/egg/sregistry/main/google_storage
copying build/lib/sregistry/main/google_storage/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_storage
copying build/lib/sregistry/main/google_storage/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_storage
copying build/lib/sregistry/main/google_storage/push.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_storage
copying build/lib/sregistry/main/google_storage/query.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_storage
copying build/lib/sregistry/main/google_storage/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_storage
copying build/lib/sregistry/main/google_storage/utils.py -> build/bdist.linux-x86_64/egg/sregistry/main/google_storage
creating build/bdist.linux-x86_64/egg/sregistry/main/hub
copying build/lib/sregistry/main/hub/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/hub
copying build/lib/sregistry/main/hub/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/hub
copying build/lib/sregistry/main/hub/query.py -> build/bdist.linux-x86_64/egg/sregistry/main/hub
copying build/lib/sregistry/main/hub/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/hub
creating build/bdist.linux-x86_64/egg/sregistry/main/nvidia
copying build/lib/sregistry/main/nvidia/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/nvidia
copying build/lib/sregistry/main/nvidia/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/nvidia
copying build/lib/sregistry/main/nvidia/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/nvidia
creating build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/auth.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/delete.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/pull.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/push.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/query.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
copying build/lib/sregistry/main/registry/record.py -> build/bdist.linux-x86_64/egg/sregistry/main/registry
creating build/bdist.linux-x86_64/egg/sregistry/main/workers
copying build/lib/sregistry/main/workers/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/main/workers
copying build/lib/sregistry/main/workers/tasks.py -> build/bdist.linux-x86_64/egg/sregistry/main/workers
copying build/lib/sregistry/main/workers/worker.py -> build/bdist.linux-x86_64/egg/sregistry/main/workers
copying build/lib/sregistry/main/README.md -> build/bdist.linux-x86_64/egg/sregistry/main
creating build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/__init__.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/cache.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/fileio.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/names.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/recipes.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/templates.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/utils/terminal.py -> build/bdist.linux-x86_64/egg/sregistry/utils
copying build/lib/sregistry/README.md -> build/bdist.linux-x86_64/egg/sregistry
byte-compiling build/bdist.linux-x86_64/egg/sregistry/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/defaults.py to defaults.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/auth/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/auth/secrets.py to secrets.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/auth/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/add.py to add.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/delete.py to delete.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/get.py to get.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/images.py to images.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/inspect.py to inspect.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/labels.py to labels.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/list.py to list.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/push.py to push.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/rm.py to rm.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/rmi.py to rmi.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/search.py to search.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/share.py to share.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/shell.py to shell.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/client/singularity.py to singularity.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/database/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/database/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/database/sqlite.py to sqlite.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/logger/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/logger/message.py to message.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/logger/progress.py to progress.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/logger/spinner.py to spinner.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/__template__/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/__template__/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/__template__/push.py to push.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/__template__/query.py to query.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/__template__/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/base/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/base/auth.py to auth.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/base/headers.py to headers.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/base/http.py to http.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/base/settings.py to settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/docker/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/docker/api.py to api.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/docker/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/docker/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/push.py to push.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/query.py to query.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/share.py to share.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_drive/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_storage/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_storage/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_storage/push.py to push.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_storage/query.py to query.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_storage/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/google_storage/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/hub/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/hub/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/hub/query.py to query.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/hub/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/nvidia/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/nvidia/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/nvidia/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/auth.py to auth.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/delete.py to delete.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/pull.py to pull.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/push.py to push.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/query.py to query.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/registry/record.py to record.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/workers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/workers/tasks.py to tasks.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/main/workers/worker.py to worker.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/cache.py to cache.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/fileio.py to fileio.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/names.py to names.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/recipes.py to recipes.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/templates.py to templates.pyc
byte-compiling build/bdist.linux-x86_64/egg/sregistry/utils/terminal.py to terminal.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sregistry.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/sregistry-0.0.6-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sregistry-0.0.6-py2.7.egg
removing '/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg
Extracting sregistry-0.0.6-py2.7.egg to /usr/lib/python2.7/site-packages
sregistry 0.0.6 is already the active version in easy-install.pth
Installing sregistry script to /usr/bin

Installed /usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg
Processing dependencies for sregistry==0.0.6
Searching for pyasn1>=0.1.7
Reading https://pypi.python.org/simple/pyasn1/
Best match: pyasn1 0.4.2
Downloading https://pypi.python.org/packages/0d/d3/ec4d56e108eee751ca4356ddff8e3c211e08e5f6ef749821c92a4b388980/pyasn1-0.4.2-py2.7.egg#md5=a54997289ab0e953b31d4c8021520600
Processing pyasn1-0.4.2-py2.7.egg
Moving pyasn1-0.4.2-py2.7.egg to /usr/lib/python2.7/site-packages
Adding pyasn1 0.4.2 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/pyasn1-0.4.2-py2.7.egg
Searching for oauth2client==3.0.0
Best match: oauth2client 3.0.0
Adding oauth2client 3.0.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for SQLAlchemy==1.2.1
Best match: SQLAlchemy 1.2.1
Adding SQLAlchemy 1.2.1 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for Pygments==2.2.0
Best match: Pygments 2.2.0
Adding Pygments 2.2.0 to easy-install.pth file
Installing pygmentize script to /usr/bin

Using /usr/lib64/python2.7/site-packages
Searching for retrying==1.3.3
Best match: retrying 1.3.3
Adding retrying 1.3.3 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for requests-toolbelt==0.8.0
Best match: requests-toolbelt 0.8.0
Adding requests-toolbelt 0.8.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for demjson==2.2.4
Best match: demjson 2.2.4
Adding demjson 2.2.4 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for dateutils==0.6.6
Best match: dateutils 0.6.6
Adding dateutils 0.6.6 to easy-install.pth file
Installing datediff script to /usr/bin
Installing dateadd script to /usr/bin

Using /usr/lib/python2.7/site-packages
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for rsa==3.4.2
Best match: rsa 3.4.2
Adding rsa 3.4.2 to easy-install.pth file
Installing pyrsa-encrypt-bigfile script to /usr/bin
Installing pyrsa-encrypt script to /usr/bin
Installing pyrsa-verify script to /usr/bin
Installing pyrsa-sign script to /usr/bin
Installing pyrsa-priv2pub script to /usr/bin
Installing pyrsa-decrypt script to /usr/bin
Installing pyrsa-decrypt-bigfile script to /usr/bin
Installing pyrsa-keygen script to /usr/bin

Using /usr/lib/python2.7/site-packages
Searching for pyasn1-modules==0.2.1
Best match: pyasn1-modules 0.2.1
Adding pyasn1-modules 0.2.1 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for httplib2==0.10.3
Best match: httplib2 0.10.3
Adding httplib2 0.10.3 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/bin

Using /usr/lib/python2.7/site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for certifi==2017.11.5
Best match: certifi 2017.11.5
Adding certifi 2017.11.5 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for pytz==2017.3
Best match: pytz 2017.3
Adding pytz 2017.3 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for python-dateutil==1.5
Best match: python-dateutil 1.5
Adding python-dateutil 1.5 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for argparse==1.4.0
Best match: argparse 1.4.0
Adding argparse 1.4.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Finished processing dependencies for sregistry==0.0.6
```

```
[root@hpcv21 sregistry-cli]# sregistry --help
ls
Traceback (most recent call last):
  File "/bin/sregistry", line 9, in <module>
    load_entry_point('sregistry==0.0.6', 'console_scripts', 'sregistry')()
  File "/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg/sregistry/client/__init__.py", line 265, in main
    from sregistry.main import Client as cli
  File "/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg/sregistry/main/__init__.py", line 26, in <module>
    from .base import ApiConnection
  File "/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg/sregistry/main/base/__init__.py", line 40, in <module>
    from sregistry.main.base.settings import (
  File "/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg/sregistry/main/base/settings.py", line 29, in <module>
    from sregistry.auth import ( read_client_secrets, update_client_secrets )
  File "/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg/sregistry/auth/__init__.py", line 1, in <module>
    from .utils import *
  File "/usr/lib/python2.7/site-packages/sregistry-0.0.6-py2.7.egg/sregistry/auth/utils.py", line 28, in <module>
    from datetime import datetime, timezone

```

There is reference of timezone in sregistry but the package timezone is not installed. I suspect version.py needs to be fixed. 
```
[root@hpcv21 sregistry-cli]# grep -iR timezone
sregistry/auth/secrets.py:from datetime import datetime, timezone
sregistry/auth/utils.py:from datetime import datetime, timezone
sregistry/auth/utils.py:    ts = datetime.now(timezone.utc)
build/lib/sregistry/auth/secrets.py:from datetime import datetime, timezone
build/lib/sregistry/auth/utils.py:from datetime import datetime, timezone
build/lib/sregistry/auth/utils.py:    ts = datetime.now(timezone.utc)
```

**Comment by vsoch** [comment]
Timezone isn't a package, it's part of datetime. What version of datetime do you have?

**Comment by shahzebsiddiqui** [comment]
[root@hpcv21 sregistry-cli]# pip list | grep DateTime
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
DateTime (4.2)

**Comment by vsoch** [comment]
Did you try pip install timezone? If that works then we can add timezone as a dependency

**Comment by dctrud** [comment]
@shahzebsiddiqui  DateTime is not what you need here - it's an implementation of something for Zope, looking at PyPi. 

datetime.timezone is definitely part of the standard library in Python 3.

I think the issue here is you are running under Python 2.7 - you need 3.x. datetime.timezone is a python3 subclass of datetime.tzinfo that isn't in python 2.7

**Comment by vsoch** [comment]
I'm going to close this, I think our discussion resolves. Thanks @dctrud !
