### ISSUE TITLE
Documentation on push for Singularity Registry is missing

### ISSUE THREAD

**Issue by bilke** [singularityhub/sregistry-cli#51]
How to push to a Singularity Registry? Also how to globally specify the URL to that registry?

It would be useful if the URL would be defined either by another environment variable and / or taken directly from the token file at `$HOME/.sregistry` when it exists.

**Comment by bilke** [comment]
I tried to push:

```bash
$ export SREGISTRY_CLIENT=registry
$ ./sregistry-cli push --name shub://sregistry.example.com/bilke/hello-world --tag latest $(./sregistry-cli get vsoch/hello-world)
[client|hub] [database|sqlite:////home/bilke/.singularity/sregistry.db]
Traceback (most recent call last):
  File "/opt/conda/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry', 'console_scripts', 'sregistry')()
  File "/opt/sregistry-cli/sregistry/client/__init__.py", line 319, in main
    subparser=subparsers[args.command])
  File "/opt/sregistry-cli/sregistry/client/push.py", line 40, in main
    response = cli.push(path=image,
AttributeError: 'Client' object has no attribute 'push'
```

Notice that the variable `SREGISTRY_CLIENT` is not taken into account. But for `shell` it is:

```
$ ./sregistry-cli shell
[client|registry] [database|sqlite:////home/bilke/.singularity/sregistry.db]
```

**Comment by vsoch** [comment]
let me take a look!

**Comment by vsoch** [comment]
okay confirmed it works with shell:

```
SREGISTRY_CLIENT=registry sregistry shell
[client|registry] [database|sqlite:////home/vanessa/.singularity/sregistry.db]
```
and shell has a push on the client

```
client.push('expfactory.simg', 'banana/pudding:shake')
```
oup just triggered a bug! The client wasn't making it through to registry because there was an import missing (I did a HUGE reorganization last night to better group dependencies). Try it now, and install from Github:

```
pip install https://github.com/singularityhub/sregistry-cli/archive/master.zip
```
The docs were entirely missing, oups! Give these a go!

https://singularityhub.github.io/sregistry-cli/client-registry#push

I did huge changes yesterday evening, so if you want to test and post any more issues that arise I'll fix them up quickly. When you are happy I'll pushed the complete fixes to another release on pypi.

**Comment by bilke** [comment]
Thanks! But how to specify the registry URL?

I had to do a:

```
$ pip install requests-toolbelt
```

Then I was able to do this:

```bash
$ sregistry push --name registry://sregistry.example.org/bilke/hello-world /home/bilke/.singularity/shub/vsoch-hello-world:latest@ed9755a0871f04db3e14971bec56a33f.simg
[client|registry] [database|sqlite:////home/bilke/.singularity/sregistry.db]
Traceback (most recent call last): 0/62 MB - 00:00:00
  File "/home/bilke/container/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.0.62', 'console_scripts', 'sregistry')()
  File "/home/bilke/container/local/lib/python3.5/site-packages/sregistry/client/__init__.py", line 319, in main
    subparser=subparsers[args.command])
  File "/home/bilke/container/local/lib/python3.5/site-packages/sregistry/client/push.py", line 42, in main
    tag=args.tag)
  File "/home/bilke/container/local/lib/python3.5/site-packages/sregistry/main/registry/push.py", line 121, in push
    r = requests.post(url, data=monitor, headers=headers)
  File "/home/bilke/container/local/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/bilke/container/local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bilke/container/local/lib/python3.5/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/bilke/container/local/lib/python3.5/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/bilke/container/local/lib/python3.5/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/bilke/container/local/lib/python3.5/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/push/': No schema supplied. Perhaps you meant http://None/push/?
```

**Comment by vsoch** [comment]
Ah! So a few notes. To install the registry dependencies, you would need to add that to the pip install, it would work like this given on pypi:

```
pip install sregistry[registry]
```
The dependencies are all separated because we assume that different users want different clients (and don't want to deal with dependencies for other clients.

For the base URL, it is read directly from your `$HOME/.sregistry` credentials file (or the one you exported to `SREGISTRY_CLIENT_SECRETS` and it looks like I need to update the singularity registry itself to use the correct format! It should look like this - a dictionary with the top key being the client (e.g, registry or nvidia):

```
cat /home/vanessa/.sregistry 
{
    "nvidia": {
    ...
    },
    "registry": {
        "base": "http://127.0.0.1",
        "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "username": "vsoch"
    },
    "google-storage": {
    ...
    },
    "hub": {
    ...
    },
    "google-drive": {
   ...
    },
```
So if you want to update that manually for now, I'll do a quick PR to update the token view.

**Comment by bilke** [comment]
Awesome now it works:

```
$pip install sregistry[registry]
[modify .sregistry]
$ sregistry push --name registry://sregistry.example.com/bilke/hello-world /home/bilke/.singularity/shub/vsoch-hello-world:latest@ed9755a0871f04db3e14971bec56a33f.simg
[client|registry] [database|sqlite:////home/bilke/.singularity/sregistry.db]
[================================] 62/62 MB - 00:00:00
[Return status 201 Created]
```

And this too:

```
$ sregistry push --name registry:bilke/hello-world /home/bilke/.singularity/shub/vsoch-hello-world:latest@ed9755a0871f04db3e14971bec56a33f.simg
[client|registry] [database|sqlite:////home/bilke/.singularity/sregistry.db]
[================================] 62/62 MB - 00:00:00
[Return status 201 Created]
```

Thanks a lot!

**Comment by vsoch** [comment]
Awesome! Thanks for catching these, and please post any more that come up.
