### ISSUE TITLE
$PATH not set correctly by pull of docker images

### ISSUE THREAD

**Issue by slefrancois** [singularityhub/sregistry-cli#79]
When pulling a docker container, the $PATH does get set correctly:
```
$ (umask 002; sregistry pull nvidia://pytorch:17.12)
$ singularity shell --nv $(sregistry get nvidia/pytorch:17.12)
Singularity: Invoking an interactive shell within container...

Singularity nvidia-pytorch:17.12.simg:~> echo $PATH
/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
```

The same operation with `singularity pull` ([using PR 1184 for nvidia cloud support](https://github.com/singularityware/singularity/pull/1184)) sets $PATH correctly:
```
$ (umask 002; singularity  pull docker://nvcr.io/nvidia/pytorch:17.12)
$ singularity shell --nv pytorch-17.12.simg
Singularity: Invoking an interactive shell within container...
Singularity pytorch-17.12.simg:~> echo $PATH
/opt/conda/envs/pytorch-py3.6/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

This is true wether building as user or root.

**Comment by vsoch** [comment]
Likely it's a missing export, I'll check this out for you when I get a chance!

**Comment by vsoch** [comment]
I'm debugging this and I can't get past an invalid token (which I just updated). Can you show me the output of the singularity (working command) with `--debug` so I can see the different headers and calls? Thanks!

**Comment by slefrancois** [comment]
I made gists:
https://gist.github.com/slefrancois/f5297093384d600969b7dcc6da0a5950
https://gist.github.com/slefrancois/568dc6c1ad1c98a17e903238055e39ad

**Comment by vsoch** [comment]
Thank you! Actually I was hoping for the --debug from when you pulled with singularity (the working command), would it be possible to share that?

**Comment by vsoch** [comment]
I just cloned the branch and am trying it again, and I can't get past the 401. The one times it works are when I have the layers cached (which I do). I'd really like to debug this but I need to get something working.

**Comment by slefrancois** [comment]
Do you mean `singularity --debug  pull docker://nvcr.io/nvidia/pytorch:17.12`? It doesn't seem to produce any extra output.

**Comment by vsoch** [comment]
Huh, is the invocation pathway still going through python? It used to show debugging output for the different urls that are pinged.

**Comment by slefrancois** [comment]
I pip installed the master and it creates a python executable:
```
$ which sregistry
$HOME/.local/bin/sregistry
$ cat $HOME/.local/bin/sregistry
#!<...>/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from sregistry.client import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

**Comment by slefrancois** [comment]
Side note, this seems to extend to other paths like the ones for libraries:
```
$ singularity shell --nv $(sregistry get nvidia/theano:17.12)
Singularity: Invoking an interactive shell within container...

Singularity nvidia-theano:17.12.simg:~> THEANO_FLAGS=device=cuda python -c "import theano"
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
In file included from /tmp/try_flags_z5pNJa.c:4:0:
/usr/include/cudnn.h:63:26: fatal error: driver_types.h: No such file or directory
compilation terminated.
```

**Comment by vsoch** [comment]
yeah so I know why the bug is there - the nvidia cloud doesn't return a version 1 manifest in the same way that Docker Hub does, there is some header mucking around with that needs to happen to get it. The version 1 manifest has the special environment variables, so as is now, any nvidia container will be lacking the environment. If there is a working singularity branch this means the correct headers were requested, and so I was asking if you could share the debug for those headers. I tried to produce this on my own but my token is invalid so I'm not able to. If you cd into your singularity folder libexec/python, and then do:

```
from docker.api import *
image = DockerApiConnection(image="nvidia/theano:17.12")
```
the output looks something like this:

```
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace: nvidia
VERBOSE Repo Name: theano
VERBOSE Repo Tag: 17.12
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/nvidia/theano/tags/list
DEBUG GET https://index.docker.io/v2/nvidia/theano/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?expires_in=9000&service=registry.docker.io&scope=repository:nvidia/theano:pull
DEBUG Headers found: Content-Type,Accept,Authorization
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?expires_in=9000&service=registry.docker.io&scope=repository:nvidia/theano:pull
DEBUG Headers found: Content-Type,Accept,Authorization
```
What I would need to do to debug is to also print the content of the headers (note how it just says they are detected). It's around like 197 of base.py in that python folder, here:

```
        header_names = ",".join(list(headers.keys()))
        bot.debug("Headers found: %s" % (header_names))
        self.headers = headers
```
You could just add a print(headers) instead. Then (removing the secrets, etc). show me what those look like  - then I can fix this. I can't get past the first call because my token is (always) invalid it seems. I really appreciate the help - the nvidia cloud has been challenging and there isn't good documentation for what the requests are expecting. One tiny change in the Content Type header with what otherwise looks like the same response can lead to totally different behavior.

**Comment by vsoch** [comment]
hey @jtriley do you have a simple example of what the header / request looked like to get the manifest version 1 to return? I'm behind a double blockade with my broken token and I need your help!

**Comment by slefrancois** [comment]
In [1]: from docker.api import *
   ...: image = DockerApiConnection(image="nvidia/pytorch:17.12")
   ...:
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 REGISTRY not defined (None)
VERBOSE2 NAMESPACE not defined (None)
VERBOSE2 SINGULARITY_DOCKER_ARCHITECTURE found as amd64
VERBOSE2 SINGULARITY_DOCKER_OS found as linux
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/env/90-environment.sh
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_HELPFILE found as None/.singularity.d/runscript.help
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_NOHTTPS found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /usr/lib/x86_64-linux-gnu/singularity/python
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as None/.singularity.d/.layers
VERBOSE2 SINGULARITY_PYTHREADS found as 9
DEBUG Headers found: Content-Type,Accept
{'Content-Type': 'application/json; charset=utf-8', 'Accept': 'application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/json'}
VERBOSE Registry: index.docker.io
VERBOSE Namespace: nvidia
VERBOSE Repo Name: pytorch
VERBOSE Repo Tag: 17.12
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/nvidia/pytorch/tags/list
DEBUG GET https://index.docker.io/v2/nvidia/pytorch/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?expires_in=9000&service=registry.docker.io&scope=repository:nvidia/pytorch:pull
DEBUG Headers found: Content-Type,Authorization,Accept
{'Content-Type': 'application/json; charset=utf-8', 'Authorization': u'Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6cFNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE56QTFNREl5TWpBME5UZGFGdzB4T0RBMU1ESXlNakEwTlRkYU1FWXhSREJDQmdOVkJBTVRPMDFPTms0NlJraFVWenBKV0VWSE9rOUpOMUU2UVRWWFJqcFpSRVUwT2pkRE4wNDZSMWRKVVRvMVZ6STNPa2hPTlVvNlZVNURRVG95U0UxQ01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU5KRklhQ1hHNWYxSk9BZnZSaTJDU081K1Q5RVpKd2doai9SUXgzNW9Uc3Q4RnhXY0dRc3ZOMG5sdW5DVVdIbENxN2I4NFJRTXV0WUVIUnY4MVhweTU2T0JzakNCcnpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VFU0MlRqcEdTRlJYT2tsWVJVYzZUMGszVVRwQk5WZEdPbGxFUlRRNk4wTTNUanBIVjBsUk9qVlhNamM2U0U0MVNqcFZUa05CT2pKSVRVSXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2xoVVVFUTZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSTJVUlpMQVRTM3R4bjNpNTY0SXVQSFEwQU1Mb1g5cTZCMmdnN01KSHJuTkFpRUE0Q3lzbmtENHhjQm42amdobVdnQzczQjdGVkszenFnOTV4ZjNRK2xGVHlrPSJdfQ.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE1MTg4MDQ5MTIsImlhdCI6MTUxODgwNDYxMiwiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiJvTUxFQlYyUHFhYmEyN1BKN0xTeiIsIm5iZiI6MTUxODgwNDMxMiwic3ViIjoiIn0.KC2PLcGEXIgQzQUsSVg_69xDPInIJ4VLaQgN1JckA_0iqgH37BLsyaPIUlukIj30GR3muEgDrI9Sat71LYT_zg', 'Accept': 'application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/json'}
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?expires_in=9000&service=registry.docker.io&scope=repository:nvidia/pytorch:pull
DEBUG Headers found: Content-Type,Authorization,Accept
{'Content-Type': 'application/json; charset=utf-8', 'Authorization': u'Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6cFNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE56QTFNREl5TWpBME5UZGFGdzB4T0RBMU1ESXlNakEwTlRkYU1FWXhSREJDQmdOVkJBTVRPMDFPTms0NlJraFVWenBKV0VWSE9rOUpOMUU2UVRWWFJqcFpSRVUwT2pkRE4wNDZSMWRKVVRvMVZ6STNPa2hPTlVvNlZVNURRVG95U0UxQ01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU5KRklhQ1hHNWYxSk9BZnZSaTJDU081K1Q5RVpKd2doai9SUXgzNW9Uc3Q4RnhXY0dRc3ZOMG5sdW5DVVdIbENxN2I4NFJRTXV0WUVIUnY4MVhweTU2T0JzakNCcnpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VFU0MlRqcEdTRlJYT2tsWVJVYzZUMGszVVRwQk5WZEdPbGxFUlRRNk4wTTNUanBIVjBsUk9qVlhNamM2U0U0MVNqcFZUa05CT2pKSVRVSXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2xoVVVFUTZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSTJVUlpMQVRTM3R4bjNpNTY0SXVQSFEwQU1Mb1g5cTZCMmdnN01KSHJuTkFpRUE0Q3lzbmtENHhjQm42amdobVdnQzczQjdGVkszenFnOTV4ZjNRK2xGVHlrPSJdfQ.eyJhY2Nlc3MiOltdLCJhdWQiOiJyZWdpc3RyeS5kb2NrZXIuaW8iLCJleHAiOjE1MTg4MDQ5MTIsImlhdCI6MTUxODgwNDYxMiwiaXNzIjoiYXV0aC5kb2NrZXIuaW8iLCJqdGkiOiIwa2tmY01UQzJvNVhNWV9XalhXbSIsIm5iZiI6MTUxODgwNDMxMiwic3ViIjoiIn0.RP2ZI_1BM9ULv5a9-ObqOn_zdDQtrKWA-4TqhuAv75dWO6yY20p4TU8MVTyUj6MyBDOtxQ1euAslFaKS3KFqJQ', 'Accept': 'application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.list.v2+json,application/json'}

**Comment by vsoch** [comment]
hey @slefrancois ! With the above, it looks like you are getting two 401 (permission denied) so I'm not sure how you are saying it works with Singularity? When I clone the branch and try, I get an SSL error.

```
singularity pull docker://ngc.io/nvidia/pytorch:17.12
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Traceback (most recent call last):
  File "/usr/local/libexec/singularity/python/import.py", line 109, in <module>
    main()
  File "/usr/local/libexec/singularity/python/import.py", line 86, in main
    layerfile=LAYERFILE)
  File "/usr/local/libexec/singularity/python/docker/main.py", line 83, in IMPORT
    client = DockerApiConnection(image=image, auth=auth)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 89, in __init__
    self.load_image(kwargs['image'])
  File "/usr/local/libexec/singularity/python/docker/api.py", line 143, in load_image
    self.update_token()
  File "/usr/local/libexec/singularity/python/docker/api.py", line 154, in update_token
    response = self.get_tags(return_response=True)
  File "/usr/local/libexec/singularity/python/docker/api.py", line 278, in get_tags
    return_response=return_response)
  File "/usr/local/libexec/singularity/python/base.py", line 302, in get
    return_response=return_response)
  File "/usr/local/libexec/singularity/python/base.py", line 318, in submit_request
    response = urlopen(request)
  File "/usr/local/libexec/singularity/python/base.py", line 166, in urlopen
    return opener.open(*args, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/libexec/singularity/python/base.py", line 161, in https_open
    return HTTPSHandler.https_open(self, req)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Cleaning up...
ERROR: pulling container failed!
```
Is there any chance we are dealing with a changing / broken Nvidia cloud?

**Comment by vsoch** [comment]
And when I don't specify the registry (and it assumes Docker Hub) this hangs:

```
singularity --debug pull docker://nvidia/pytorch:17.12
```

**Comment by vsoch** [comment]
oh I think I can get this working!! I just figure out the headers! AHH

**Comment by vsoch** [comment]
Found it!! :D 

```
['PATH=/opt/conda/envs/pytorch-py3.6/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'CUDA_VERSION=9.0.176',
 'CUDA_VERSION_WAR1936603=9.0.176_384.81',
 'CUDA_PKG_VERSION=9-0=9.0.176-1',
 'NCCL_VERSION=2.1.2',
 'NCCL_PKG_VERSION=2.1.2-1+cuda9.0',
 'CUBLAS_VERSION_WAR1936603=9.0.234_384.99',
 'CUBLAS_PKG_VERSION=9-0=9.0.234-1',
 'LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
 'LIBRARY_PATH=/usr/local/cuda/lib64/stubs:',
 'CUDNN_VERSION=7.0.5',
 'CUDNN_VERSION_BUILD=7.0.5.15',
 'PYTORCH_VERSION=0.2+',
 'NVIDIA_PYTORCH_VERSION=17.12',
 'PYTHON_VERSION=3.6',
 'LANG=C.UTF-8',
 'NVIDIA_BUILD_ID=242055']
```

**Comment by vsoch** [comment]
woohoo! I think I got it!

Do the pull (and force to replace old image with no path)
```
sregistry pull --force nvidia://pytorch:17.12
[client|nvidia] [database|sqlite:////home/vanessa/.singularity/sregistry.db]
Exploding /usr/local/libexec/singularity/bootstrap-scripts/environment.tar
Exploding /home/vanessa/.singularity/docker/sha256:8d51e945c435c97df0eb04e5c9caff1d6c99eb8a3030e18a04a5923a1b1abdd0.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:d8d21cdaac84d0be27d5550019257c1d06ba7f99d9ec1320391b9f9cd799d097.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:99b5ff394311a271f361f962519279e205355960833368b925a436cb34eb2707.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:3ab3190bc52d76fe2bedebaa0a5b86c12de0fe88a8a5d6885a4abcfe2b351369.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:8f2bd7981235ff4f6211fe0df2d15f960912138be583f10e4bd000d804dc7f91.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:b38e947b0f59036727b7ab42fe81294a59ab468ad356cca86581c7f921e51616.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:5f3368de62b2ebba41fe57373952367419aedd6efe65e53297fa079f4d5898e6.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:3ab1c96a3f8c6420a4a4a29ec15767b96b4be33e6fbb69f6096a6b4a1b312d5e.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:68b371383ef8c6ae9ef2cf518ee2d4a8a04de00c4a9e209d21a7494cf7b334d3.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:4a66d7263564f72a60b93fec2d48da356434aa8f1005a68b1d0681e2b8e1a7b0.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:c331d3cc3c1cf029cbc5e3f9ea7cf06d25fba9156e9a05c548209006145ebef5.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:b79da51ea9de5c94351ba76e3b36a9ba58ee87ff8b292db60c03c56942434d30.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:3decda390899099e6732c0beca5750f95caeccb9011360291e2a762cd0567b3d.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:ee4420662a6174c05e585055fbd41434b846bcb4618327774d7157717a5302cd.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:84265a8d7208110071650ed9346860f9da53867ab651d58b5f2b1e56e95fd080.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:7566e5cca350e158c564cf232d17699e6ef085b87c1c3bbd97e3c9188b7b2537.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:5550205f4a6aade93e19d0886f1fce243f746dd41de138061ab7e1644d7a3d2f.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:895699c756c066ac3fa60a2ad1bab653eef1a7bd5e7489bc8e577c2960a4d71e.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:1b8b06f8a0b5f92331114841ab4ea5526b4377878584417e7cb2ad5a7691beeb.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:1621c5a736d140a25f90d70209d8ccaa69911c0582de726cb0be2ce4e1ff3c66.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:184de4141a335d0857c6d919806414e098ca2bd10382611a7fbddd454c8a9e7f.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a373c14001979ef23b5bb7167c63b37a1e595ad098d3365e92b720391ad0a033.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:0ddc4591ddccfbd0af497a55d9d2a622d2b3a60855c32dc02dbca70d141dcfeb.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:519c965cd6f5686abfd50fbcb1ab4992499c07a5e0857b9e27359ff64ef79625.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:170436260c309235b0ee638fdb8fcabd4cfd68b06d8fab1148709ea07e1e8ee4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:321e0b4e643343e4a54c38db43da66b34a6407609db93cd1240d94f7a42dd161.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:2787ea8d66bfae5bfb2f7de064d96b07e63d44f912149298a17861063da9b20b.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:95cf83103251fbb852b2ed28f0ca0466443b1e839278166b4d320c2b6e84c7ec.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:65ba4328bf16260824a3eda9e123354df148e6afbaffac96653e7aa33a5a7f88.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:343cd4761f8bfdb3f4d8be82274ad723f759728743940b56da9d8bbe2b132f15.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:87bac98175b8a8c48f1f0ec99370a1f9f10dcc816a6c7553c9d21af9458a52ba.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar.gz
Exploding /home/vanessa/.singularity/docker/metadata/sha256:4912449df8b47bf681da537310f54002c9254c33cbd3f4028ccd195450a3b646.tar.gz

Building into existing container: /home/vanessa/.singularity/shub/nvidia-pytorch:17.12.simg
WARNING: Building container as an unprivileged user. If you run this container as root
WARNING: it may be missing some functionality.
Building FS image from sandbox: /tmp/tmp4r8sldpl
Building Singularity FS image...
Building Singularity SIF container image...
Singularity container built: /home/vanessa/.singularity/shub/nvidia-pytorch:17.12.simg
Cleaning up...

[container][new] nvidia/pytorch:17.12
Success! /home/vanessa/.singularity/shub/nvidia-pytorch:17.12.simg

```
Now shell and look at guts...
```
vanessa@vanessa-ThinkPad-T460s:~/Documents/Dropbox/Code/sregistry/sregistry-cli$ singularity shell --nv $(sregistry get nvidia/pytorch:17.12)
WARNING: Could not find the Nvidia SMI binary to bind into container

Singularity: Invoking an interactive shell within container...

Singularity nvidia-pytorch:17.12.simg:~/Documents/Dropbox/Code/sregistry/sregistry-cli> 
Singularity nvidia-pytorch:17.12.simg:~/Documents/Dropbox/Code/sregistry/sregistry-cli> echo $PATH
/opt/conda/envs/pytorch-py3.6/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by vsoch** [comment]
hey @slefrancois I have opened a PR for you!

https://github.com/singularityhub/sregistry-cli/pull/81

It's on a separate branch that addresses the issue, so if you are able to test, it would be lovely! You can install from the branch (make sure to completely remove any old sregistry so there isn't crossing of libraries - this just happened to me and it was confusing) and then test away!
